services:
  blog-backend:
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: npm run dev

  blog-frontend:
    build:
      context: ./frontend
      target: build
    environment:
      VITE_BACKEND_URL: ${VITE_BACKEND_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports: !override
      - "3000:5173"
    command: npm run dev -- --host 0.0.0.0